Traceback (most recent call last):
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def go_to_newline():
    print()

def print_same_line(x):
    print(x, end='')

def print_asterisk(n):
    if n > 0:
        print_asterisk(n - 1)
        print_same_line("*")

def print_diamond(n):
    if n % 2 == 0:
        n += 1
    for i in range(1, n + 1, 2):
        pattern((n - i) // 2)
        print_asterisk(i)
        go_to_newline()
    for i in range(n - 2, 0, -2):
        pattern((n - i) // 2)
        print_asterisk(i)
        go_to_newline()

# Example usage:
print_diamond(5)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRecursionError[0m                            Traceback (most recent call last)
File [0;32m~/opt/anaconda3/lib/python3.9/threading.py:1073[0m, in [0;36mThread._wait_for_tstate_lock[0;34m(self, block, timeout)[0m
[1;32m   1072[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1073[0m     [38;5;28;01mif[39;00m [43mlock[49m[38;5;241;43m.[39;49m[43macquire[49m[43m([49m[43mblock[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m:
[1;32m   1074[0m         lock[38;5;241m.[39mrelease()

[0;31mRecursionError[0m: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

[0;31mRecursionError[0m                            Traceback (most recent call last)
Input [0;32mIn [9][0m, in [0;36m<cell line: 25>[0;34m()[0m
[1;32m     22[0m         go_to_newline()
[1;32m     24[0m [38;5;66;03m# Example usage:[39;00m
[0;32m---> 25[0m [43mprint_diamond[49m[43m([49m[38;5;241;43m5[39;49m[43m)[49m

Input [0;32mIn [9][0m, in [0;36mprint_diamond[0;34m(n)[0m
[1;32m     14[0m     n [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m     15[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m1[39m, n [38;5;241m+[39m [38;5;241m1[39m, [38;5;241m2[39m):
[0;32m---> 16[0m     [43mpattern[49m[43m([49m[43m([49m[43mn[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[43mi[49m[43m)[49m[43m [49m[38;5;241;43m/[39;49m[38;5;241;43m/[39;49m[43m [49m[38;5;241;43m2[39;49m[43m)[49m
[1;32m     17[0m     print_asterisk(i)
[1;32m     18[0m     go_to_newline()

Input [0;32mIn [8][0m, in [0;36mpattern[0;34m(n)[0m
[1;32m     21[0m [38;5;28;01mdef[39;00m [38;5;21mpattern[39m(n):
[0;32m---> 22[0m    [43mprint_space[49m[43m([49m[43mn[49m[38;5;241;43m-[39;49m[38;5;241;43m1[39;49m[43m)[49m

Input [0;32mIn [8][0m, in [0;36mprint_space[0;34m(space)[0m
[1;32m     16[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[1;32m     17[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[0;32m---> 18[0m [43mprint_space[49m[43m([49m[43mspace[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[38;5;241;43m1[39;49m[43m)[49m

Input [0;32mIn [8][0m, in [0;36mprint_space[0;34m(space)[0m
[1;32m     16[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[1;32m     17[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[0;32m---> 18[0m [43mprint_space[49m[43m([49m[43mspace[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[38;5;241;43m1[39;49m[43m)[49m

    [0;31m[... skipping similar frames: print_space at line 18 (2962 times)][0m

Input [0;32mIn [8][0m, in [0;36mprint_space[0;34m(space)[0m
[1;32m     16[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[1;32m     17[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[0;32m---> 18[0m [43mprint_space[49m[43m([49m[43mspace[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[38;5;241;43m1[39;49m[43m)[49m

Input [0;32mIn [8][0m, in [0;36mprint_space[0;34m(space)[0m
[1;32m     14[0m [38;5;28;01mif[39;00m (space [38;5;241m==[39m [38;5;241m0[39m):
[1;32m     15[0m     [38;5;28;01mreturn[39;00m;
[0;32m---> 16[0m [38;5;28;43mprint[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m [39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mend[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[43m)[49m;
[1;32m     17[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, end [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m);
[1;32m     18[0m print_space(space [38;5;241m-[39m [38;5;241m1[39m)

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/ipykernel/iostream.py:531[0m, in [0;36mOutStream.write[0;34m(self, string)[0m
[1;32m    529[0m is_child [38;5;241m=[39m ([38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_master_process())
[1;32m    530[0m [38;5;66;03m# only touch the buffer in the IO thread to avoid races[39;00m
[0;32m--> 531[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpub_thread[49m[38;5;241;43m.[39;49m[43mschedule[49m[43m([49m[38;5;28;43;01mlambda[39;49;00m[43m:[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_buffer[49m[38;5;241;43m.[39;49m[43mwrite[49m[43m([49m[43mstring[49m[43m)[49m[43m)[49m
[1;32m    532[0m [38;5;28;01mif[39;00m is_child:
[1;32m    533[0m     [38;5;66;03m# mp.Pool cannot be trusted to flush promptly (or ever),[39;00m
[1;32m    534[0m     [38;5;66;03m# and this helps.[39;00m
[1;32m    535[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_subprocess_flush_pending:

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/ipykernel/iostream.py:213[0m, in [0;36mIOPubThread.schedule[0;34m(self, f)[0m
[1;32m    208[0m [38;5;28;01mdef[39;00m [38;5;21mschedule[39m([38;5;28mself[39m, f):
[1;32m    209[0m     [38;5;124;03m"""Schedule a function to be called in our IO thread.[39;00m
[1;32m    210[0m 
[1;32m    211[0m [38;5;124;03m    If the thread is not running, call immediately.[39;00m
[1;32m    212[0m [38;5;124;03m    """[39;00m
[0;32m--> 213[0m     [38;5;28;01mif[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mthread[49m[38;5;241;43m.[39;49m[43mis_alive[49m[43m([49m[43m)[49m:
[1;32m    214[0m         [38;5;28mself[39m[38;5;241m.[39m_events[38;5;241m.[39mappend(f)
[1;32m    215[0m         [38;5;66;03m# wake event thread (message content is ignored)[39;00m

File [0;32m~/opt/anaconda3/lib/python3.9/threading.py:1137[0m, in [0;36mThread.is_alive[0;34m(self)[0m
[1;32m   1135[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_stopped [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_started[38;5;241m.[39mis_set():
[1;32m   1136[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mFalse[39;00m
[0;32m-> 1137[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_wait_for_tstate_lock[49m[43m([49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[1;32m   1138[0m [38;5;28;01mreturn[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_stopped

File [0;32m~/opt/anaconda3/lib/python3.9/threading.py:1077[0m, in [0;36mThread._wait_for_tstate_lock[0;34m(self, block, timeout)[0m
[1;32m   1075[0m         [38;5;28mself[39m[38;5;241m.[39m_stop()
[1;32m   1076[0m [38;5;28;01mexcept[39;00m:
[0;32m-> 1077[0m     [38;5;28;01mif[39;00m [43mlock[49m[38;5;241;43m.[39;49m[43mlocked[49m[43m([49m[43m)[49m:
[1;32m   1078[0m         [38;5;66;03m# bpo-45274: lock.acquire() acquired the lock, but the function[39;00m
[1;32m   1079[0m         [38;5;66;03m# was interrupted with an exception before reaching the[39;00m
[1;32m   1080[0m         [38;5;66;03m# lock.release(). It can happen if a signal handler raises an[39;00m
[1;32m   1081[0m         [38;5;66;03m# exception, like CTRL+C which raises KeyboardInterrupt.[39;00m
[1;32m   1082[0m         lock[38;5;241m.[39mrelease()
[1;32m   1083[0m         [38;5;28mself[39m[38;5;241m.[39m_stop()

[0;31mRecursionError[0m: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object

